//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.MANAGESCPOPALLETITEMIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPalletItemGrResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPalletItemList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string mATNRField;
        
        private string aRKTXField;
        
        private decimal uMREZField;
        
        private bool uMREZFieldSpecified;
        
        private decimal bOXQTYField;
        
        private bool bOXQTYFieldSpecified;
        
        private decimal lFIMGField;
        
        private bool lFIMGFieldSpecified;
        
        private string vRKMEField;
        
        private decimal lFIMGCField;
        
        private bool lFIMGCFieldSpecified;
        
        private decimal lFIMGDField;
        
        private bool lFIMGDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
                this.RaisePropertyChanged("POSNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ARKTX {
            get {
                return this.aRKTXField;
            }
            set {
                this.aRKTXField = value;
                this.RaisePropertyChanged("ARKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal UMREZ {
            get {
                return this.uMREZField;
            }
            set {
                this.uMREZField = value;
                this.RaisePropertyChanged("UMREZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UMREZSpecified {
            get {
                return this.uMREZFieldSpecified;
            }
            set {
                this.uMREZFieldSpecified = value;
                this.RaisePropertyChanged("UMREZSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal BOXQTY {
            get {
                return this.bOXQTYField;
            }
            set {
                this.bOXQTYField = value;
                this.RaisePropertyChanged("BOXQTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BOXQTYSpecified {
            get {
                return this.bOXQTYFieldSpecified;
            }
            set {
                this.bOXQTYFieldSpecified = value;
                this.RaisePropertyChanged("BOXQTYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal LFIMG {
            get {
                return this.lFIMGField;
            }
            set {
                this.lFIMGField = value;
                this.RaisePropertyChanged("LFIMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LFIMGSpecified {
            get {
                return this.lFIMGFieldSpecified;
            }
            set {
                this.lFIMGFieldSpecified = value;
                this.RaisePropertyChanged("LFIMGSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VRKME {
            get {
                return this.vRKMEField;
            }
            set {
                this.vRKMEField = value;
                this.RaisePropertyChanged("VRKME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal LFIMGC {
            get {
                return this.lFIMGCField;
            }
            set {
                this.lFIMGCField = value;
                this.RaisePropertyChanged("LFIMGC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LFIMGCSpecified {
            get {
                return this.lFIMGCFieldSpecified;
            }
            set {
                this.lFIMGCFieldSpecified = value;
                this.RaisePropertyChanged("LFIMGCSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal LFIMGD {
            get {
                return this.lFIMGDField;
            }
            set {
                this.lFIMGDField = value;
                this.RaisePropertyChanged("LFIMGD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LFIMGDSpecified {
            get {
                return this.lFIMGDFieldSpecified;
            }
            set {
                this.lFIMGDFieldSpecified = value;
                this.RaisePropertyChanged("LFIMGDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPalletItemGrQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pALETField;
        
        private string wERKSField;
        
        private System.DateTime bUDATField;
        
        private bool bUDATFieldSpecified;
        
        private ScPalletItemList[] scPalletItemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PALET {
            get {
                return this.pALETField;
            }
            set {
                this.pALETField = value;
                this.RaisePropertyChanged("PALET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
                this.RaisePropertyChanged("BUDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUDATSpecified {
            get {
                return this.bUDATFieldSpecified;
            }
            set {
                this.bUDATFieldSpecified = value;
                this.RaisePropertyChanged("BUDATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScPalletItemList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ScPalletItemList[] ScPalletItemList {
            get {
                return this.scPalletItemListField;
            }
            set {
                this.scPalletItemListField = value;
                this.RaisePropertyChanged("ScPalletItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/MOB", ConfigurationName="MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn")]
    public interface ManageScPoPalletItemIn {
        
        // CODEGEN: Generating message contract since the operation ScPalletItemGrQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse ScPalletItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse> ScPalletItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest request);
        
        // CODEGEN: Generating message contract since the operation ScPoItemDpQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse ScPoItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse> ScPoItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest request);
        
        // CODEGEN: Generating message contract since the operation ScPalletItemDpQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse ScPalletItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse> ScPalletItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest request);
        
        // CODEGEN: Generating message contract since the operation ScPoItemGrQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse ScPoItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse> ScPoItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPalletItemGrQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQuery_sync ScPalletItemGrQuery_sync;
        
        public ScPalletItemGrQueryResponse_InRequest() {
        }
        
        public ScPalletItemGrQueryResponse_InRequest(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQuery_sync ScPalletItemGrQuery_sync) {
            this.ScPalletItemGrQuery_sync = ScPalletItemGrQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPalletItemGrQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrResponse_sync ScPalletItemGrResponse_sync;
        
        public ScPalletItemGrQueryResponse_InResponse() {
        }
        
        public ScPalletItemGrQueryResponse_InResponse(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrResponse_sync ScPalletItemGrResponse_sync) {
            this.ScPalletItemGrResponse_sync = ScPalletItemGrResponse_sync;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPoItemDpQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eBELNField;
        
        private string wERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPoItemDpResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        private ScPoItemList[] scPoItemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScPoItemList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ScPoItemList[] ScPoItemList {
            get {
                return this.scPoItemListField;
            }
            set {
                this.scPoItemListField = value;
                this.RaisePropertyChanged("ScPoItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPoItemList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eBELPField;
        
        private string lIFNRField;
        
        private string nAME1Field;
        
        private string mATNRField;
        
        private string tXZ01Field;
        
        private decimal mENGEField;
        
        private bool mENGEFieldSpecified;
        
        private string mEINSField;
        
        private decimal nETPRField;
        
        private bool nETPRFieldSpecified;
        
        private decimal nETWRField;
        
        private bool nETWRFieldSpecified;
        
        private decimal uMREZField;
        
        private bool uMREZFieldSpecified;
        
        private string lOEVMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TXZ01 {
            get {
                return this.tXZ01Field;
            }
            set {
                this.tXZ01Field = value;
                this.RaisePropertyChanged("TXZ01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
                this.RaisePropertyChanged("MENGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MENGESpecified {
            get {
                return this.mENGEFieldSpecified;
            }
            set {
                this.mENGEFieldSpecified = value;
                this.RaisePropertyChanged("MENGESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal NETPR {
            get {
                return this.nETPRField;
            }
            set {
                this.nETPRField = value;
                this.RaisePropertyChanged("NETPR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETPRSpecified {
            get {
                return this.nETPRFieldSpecified;
            }
            set {
                this.nETPRFieldSpecified = value;
                this.RaisePropertyChanged("NETPRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal NETWR {
            get {
                return this.nETWRField;
            }
            set {
                this.nETWRField = value;
                this.RaisePropertyChanged("NETWR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETWRSpecified {
            get {
                return this.nETWRFieldSpecified;
            }
            set {
                this.nETWRFieldSpecified = value;
                this.RaisePropertyChanged("NETWRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal UMREZ {
            get {
                return this.uMREZField;
            }
            set {
                this.uMREZField = value;
                this.RaisePropertyChanged("UMREZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UMREZSpecified {
            get {
                return this.uMREZFieldSpecified;
            }
            set {
                this.uMREZFieldSpecified = value;
                this.RaisePropertyChanged("UMREZSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string LOEVM {
            get {
                return this.lOEVMField;
            }
            set {
                this.lOEVMField = value;
                this.RaisePropertyChanged("LOEVM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPoItemDpQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQuery_sync ScPoItemDpQuery_sync;
        
        public ScPoItemDpQueryResponse_InRequest() {
        }
        
        public ScPoItemDpQueryResponse_InRequest(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQuery_sync ScPoItemDpQuery_sync) {
            this.ScPoItemDpQuery_sync = ScPoItemDpQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPoItemDpQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpResponse_sync ScPoItemDpResponse_syn;
        
        public ScPoItemDpQueryResponse_InResponse() {
        }
        
        public ScPoItemDpQueryResponse_InResponse(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpResponse_sync ScPoItemDpResponse_syn) {
            this.ScPoItemDpResponse_syn = ScPoItemDpResponse_syn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPalletItemDpQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pALETField;
        
        private string wERKSField;
        
        private System.DateTime bUDATField;
        
        private bool bUDATFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PALET {
            get {
                return this.pALETField;
            }
            set {
                this.pALETField = value;
                this.RaisePropertyChanged("PALET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
                this.RaisePropertyChanged("BUDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUDATSpecified {
            get {
                return this.bUDATFieldSpecified;
            }
            set {
                this.bUDATFieldSpecified = value;
                this.RaisePropertyChanged("BUDATSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPalletItemDpResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        private ScPalletItemList[] scPalletItemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScPalletItemList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ScPalletItemList[] ScPalletItemList {
            get {
                return this.scPalletItemListField;
            }
            set {
                this.scPalletItemListField = value;
                this.RaisePropertyChanged("ScPalletItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPalletItemDpQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQuery_sync ScPalletItemDpQuery_sync;
        
        public ScPalletItemDpQueryResponse_InRequest() {
        }
        
        public ScPalletItemDpQueryResponse_InRequest(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQuery_sync ScPalletItemDpQuery_sync) {
            this.ScPalletItemDpQuery_sync = ScPalletItemDpQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPalletItemDpQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpResponse_sync ScPalletItemDpResponse_sync;
        
        public ScPalletItemDpQueryResponse_InResponse() {
        }
        
        public ScPalletItemDpQueryResponse_InResponse(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpResponse_sync ScPalletItemDpResponse_sync) {
            this.ScPalletItemDpResponse_sync = ScPalletItemDpResponse_sync;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPoItemGrQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eBELNField;
        
        private string wERKSField;
        
        private System.DateTime bUDATField;
        
        private bool bUDATFieldSpecified;
        
        private ScPoItemList[] scPoItemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
                this.RaisePropertyChanged("BUDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUDATSpecified {
            get {
                return this.bUDATFieldSpecified;
            }
            set {
                this.bUDATFieldSpecified = value;
                this.RaisePropertyChanged("BUDATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScPoItemList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ScPoItemList[] ScPoItemList {
            get {
                return this.scPoItemListField;
            }
            set {
                this.scPoItemListField = value;
                this.RaisePropertyChanged("ScPoItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ScPoItemGrResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPoItemGrQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQuery_sync ScPoItemGrQuery_sync;
        
        public ScPoItemGrQueryResponse_InRequest() {
        }
        
        public ScPoItemGrQueryResponse_InRequest(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQuery_sync ScPoItemGrQuery_sync) {
            this.ScPoItemGrQuery_sync = ScPoItemGrQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScPoItemGrQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrResponse_sync ScPoItemGrResponse_sync;
        
        public ScPoItemGrQueryResponse_InResponse() {
        }
        
        public ScPoItemGrQueryResponse_InResponse(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrResponse_sync ScPoItemGrResponse_sync) {
            this.ScPoItemGrResponse_sync = ScPoItemGrResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageScPoPalletItemInChannel : Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageScPoPalletItemInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn>, Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn {
        
        public ManageScPoPalletItemInClient() {
        }
        
        public ManageScPoPalletItemInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageScPoPalletItemInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageScPoPalletItemInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageScPoPalletItemInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPalletItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest request) {
            return base.Channel.ScPalletItemGrQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrResponse_sync ScPalletItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQuery_sync ScPalletItemGrQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest();
            inValue.ScPalletItemGrQuery_sync = ScPalletItemGrQuery_sync;
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPalletItemGrQueryResponse_In(inValue);
            return retVal.ScPalletItemGrResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse> Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPalletItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest request) {
            return base.Channel.ScPalletItemGrQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InResponse> ScPalletItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQuery_sync ScPalletItemGrQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemGrQueryResponse_InRequest();
            inValue.ScPalletItemGrQuery_sync = ScPalletItemGrQuery_sync;
            return ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPalletItemGrQueryResponse_InAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPoItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest request) {
            return base.Channel.ScPoItemDpQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpResponse_sync ScPoItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQuery_sync ScPoItemDpQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest();
            inValue.ScPoItemDpQuery_sync = ScPoItemDpQuery_sync;
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPoItemDpQueryResponse_In(inValue);
            return retVal.ScPoItemDpResponse_syn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse> Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPoItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest request) {
            return base.Channel.ScPoItemDpQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InResponse> ScPoItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQuery_sync ScPoItemDpQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemDpQueryResponse_InRequest();
            inValue.ScPoItemDpQuery_sync = ScPoItemDpQuery_sync;
            return ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPoItemDpQueryResponse_InAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPalletItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest request) {
            return base.Channel.ScPalletItemDpQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpResponse_sync ScPalletItemDpQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQuery_sync ScPalletItemDpQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest();
            inValue.ScPalletItemDpQuery_sync = ScPalletItemDpQuery_sync;
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPalletItemDpQueryResponse_In(inValue);
            return retVal.ScPalletItemDpResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse> Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPalletItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest request) {
            return base.Channel.ScPalletItemDpQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InResponse> ScPalletItemDpQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQuery_sync ScPalletItemDpQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPalletItemDpQueryResponse_InRequest();
            inValue.ScPalletItemDpQuery_sync = ScPalletItemDpQuery_sync;
            return ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPalletItemDpQueryResponse_InAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPoItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest request) {
            return base.Channel.ScPoItemGrQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrResponse_sync ScPoItemGrQueryResponse_In(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQuery_sync ScPoItemGrQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest();
            inValue.ScPoItemGrQuery_sync = ScPoItemGrQuery_sync;
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPoItemGrQueryResponse_In(inValue);
            return retVal.ScPoItemGrResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse> Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn.ScPoItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest request) {
            return base.Channel.ScPoItemGrQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InResponse> ScPoItemGrQueryResponse_InAsync(Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQuery_sync ScPoItemGrQuery_sync) {
            Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ScPoItemGrQueryResponse_InRequest();
            inValue.ScPoItemGrQuery_sync = ScPoItemGrQuery_sync;
            return ((Eland.NRSM.Template.MANAGESCPOPALLETITEMIN.ManageScPoPalletItemIn)(this)).ScPoItemGrQueryResponse_InAsync(inValue);
        }
    }
}
