//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.MANAGEMANUALORDERIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class SaveManualOrderResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ManualOrderMatInfoList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wERKSField;
        
        private string mATNRField;
        
        private string mATNR1Field;
        
        private string mAKTXField;
        
        private string mTARTField;
        
        private System.DateTime bEDATField;
        
        private string pERNOField;
        
        private decimal mENGEField;
        
        private string mEINSField;
        
        private string wEKGRField;
        
        private string bWSCLField;
        
        private string bWSCL_TXField;
        
        private decimal pLIFZField;
        
        private decimal lABSTField;
        
        private decimal uMREZField;
        
        private decimal tOQTYField;
        
        private decimal yEQTYField;
        
        private decimal oPENPOField;
        
        private string nOCTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATNR1 {
            get {
                return this.mATNR1Field;
            }
            set {
                this.mATNR1Field = value;
                this.RaisePropertyChanged("MATNR1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
                this.RaisePropertyChanged("MAKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MTART {
            get {
                return this.mTARTField;
            }
            set {
                this.mTARTField = value;
                this.RaisePropertyChanged("MTART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime BEDAT {
            get {
                return this.bEDATField;
            }
            set {
                this.bEDATField = value;
                this.RaisePropertyChanged("BEDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PERNO {
            get {
                return this.pERNOField;
            }
            set {
                this.pERNOField = value;
                this.RaisePropertyChanged("PERNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
                this.RaisePropertyChanged("MENGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string WEKGR {
            get {
                return this.wEKGRField;
            }
            set {
                this.wEKGRField = value;
                this.RaisePropertyChanged("WEKGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BWSCL {
            get {
                return this.bWSCLField;
            }
            set {
                this.bWSCLField = value;
                this.RaisePropertyChanged("BWSCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BWSCL_TX {
            get {
                return this.bWSCL_TXField;
            }
            set {
                this.bWSCL_TXField = value;
                this.RaisePropertyChanged("BWSCL_TX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal PLIFZ {
            get {
                return this.pLIFZField;
            }
            set {
                this.pLIFZField = value;
                this.RaisePropertyChanged("PLIFZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal LABST {
            get {
                return this.lABSTField;
            }
            set {
                this.lABSTField = value;
                this.RaisePropertyChanged("LABST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal UMREZ {
            get {
                return this.uMREZField;
            }
            set {
                this.uMREZField = value;
                this.RaisePropertyChanged("UMREZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal TOQTY {
            get {
                return this.tOQTYField;
            }
            set {
                this.tOQTYField = value;
                this.RaisePropertyChanged("TOQTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal YEQTY {
            get {
                return this.yEQTYField;
            }
            set {
                this.yEQTYField = value;
                this.RaisePropertyChanged("YEQTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal OPENPO {
            get {
                return this.oPENPOField;
            }
            set {
                this.oPENPOField = value;
                this.RaisePropertyChanged("OPENPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string NOCTL {
            get {
                return this.nOCTLField;
            }
            set {
                this.nOCTLField = value;
                this.RaisePropertyChanged("NOCTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class SaveManualOrderQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ManualOrderMatInfoList manualOrderMatInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ManualOrderMatInfoList ManualOrderMatInfoList {
            get {
                return this.manualOrderMatInfoListField;
            }
            set {
                this.manualOrderMatInfoListField = value;
                this.RaisePropertyChanged("ManualOrderMatInfoList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/MOB", ConfigurationName="MANAGEMANUALORDERIN.ManageManualOrderIn")]
    public interface ManageManualOrderIn {
        
        // CODEGEN: 操作 SaveManualOrderQueryResponse_In 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGEMANUALORDERIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse SaveManualOrderQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse> SaveManualOrderQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest request);
        
        // CODEGEN: 操作 ManualOrderMatInfoQueryResponse_In 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.MANAGEMANUALORDERIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse ManualOrderMatInfoQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse> ManualOrderMatInfoQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveManualOrderQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQuery_sync SaveManualOrderQuery_sync;
        
        public SaveManualOrderQueryResponse_InRequest() {
        }
        
        public SaveManualOrderQueryResponse_InRequest(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQuery_sync SaveManualOrderQuery_sync) {
            this.SaveManualOrderQuery_sync = SaveManualOrderQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveManualOrderQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderResponse_sync SaveManualOrderResponse_sync;
        
        public SaveManualOrderQueryResponse_InResponse() {
        }
        
        public SaveManualOrderQueryResponse_InResponse(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderResponse_sync SaveManualOrderResponse_sync) {
            this.SaveManualOrderResponse_sync = SaveManualOrderResponse_sync;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ManualOrderMatInfoQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wERKSField;
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class ManualOrderMatInfoResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ManualOrderMatInfoList[] manualOrderMatInfoListField;
        
        private string flagField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManualOrderMatInfoList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ManualOrderMatInfoList[] ManualOrderMatInfoList {
            get {
                return this.manualOrderMatInfoListField;
            }
            set {
                this.manualOrderMatInfoListField = value;
                this.RaisePropertyChanged("ManualOrderMatInfoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ManualOrderMatInfoQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQuery_sync ManualOrderMatInfoQuery_sync;
        
        public ManualOrderMatInfoQueryResponse_InRequest() {
        }
        
        public ManualOrderMatInfoQueryResponse_InRequest(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQuery_sync ManualOrderMatInfoQuery_sync) {
            this.ManualOrderMatInfoQuery_sync = ManualOrderMatInfoQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ManualOrderMatInfoQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoResponse_sync ManualOrderMatInfoResponse_sync;
        
        public ManualOrderMatInfoQueryResponse_InResponse() {
        }
        
        public ManualOrderMatInfoQueryResponse_InResponse(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoResponse_sync ManualOrderMatInfoResponse_sync) {
            this.ManualOrderMatInfoResponse_sync = ManualOrderMatInfoResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageManualOrderInChannel : Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageManualOrderInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn>, Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn {
        
        public ManageManualOrderInClient() {
        }
        
        public ManageManualOrderInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageManualOrderInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageManualOrderInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageManualOrderInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn.SaveManualOrderQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest request) {
            return base.Channel.SaveManualOrderQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderResponse_sync SaveManualOrderQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQuery_sync SaveManualOrderQuery_sync) {
            Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest();
            inValue.SaveManualOrderQuery_sync = SaveManualOrderQuery_sync;
            Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn)(this)).SaveManualOrderQueryResponse_In(inValue);
            return retVal.SaveManualOrderResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse> Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn.SaveManualOrderQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest request) {
            return base.Channel.SaveManualOrderQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InResponse> SaveManualOrderQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQuery_sync SaveManualOrderQuery_sync) {
            Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGEMANUALORDERIN.SaveManualOrderQueryResponse_InRequest();
            inValue.SaveManualOrderQuery_sync = SaveManualOrderQuery_sync;
            return ((Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn)(this)).SaveManualOrderQueryResponse_InAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn.ManualOrderMatInfoQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest request) {
            return base.Channel.ManualOrderMatInfoQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoResponse_sync ManualOrderMatInfoQueryResponse_In(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQuery_sync ManualOrderMatInfoQuery_sync) {
            Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest();
            inValue.ManualOrderMatInfoQuery_sync = ManualOrderMatInfoQuery_sync;
            Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse retVal = ((Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn)(this)).ManualOrderMatInfoQueryResponse_In(inValue);
            return retVal.ManualOrderMatInfoResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse> Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn.ManualOrderMatInfoQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest request) {
            return base.Channel.ManualOrderMatInfoQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InResponse> ManualOrderMatInfoQueryResponse_InAsync(Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQuery_sync ManualOrderMatInfoQuery_sync) {
            Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest inValue = new Eland.NRSM.Template.MANAGEMANUALORDERIN.ManualOrderMatInfoQueryResponse_InRequest();
            inValue.ManualOrderMatInfoQuery_sync = ManualOrderMatInfoQuery_sync;
            return ((Eland.NRSM.Template.MANAGEMANUALORDERIN.ManageManualOrderIn)(this)).ManualOrderMatInfoQueryResponse_InAsync(inValue);
        }
    }
}
