//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZMANAGESPACEPROFITIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class SpaceProfitByCurrentIDResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMessageField;
        
        private decimal areaField;
        
        private bool areaFieldSpecified;
        
        private decimal spaceProfitField;
        
        private bool spaceProfitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AreaSpecified {
            get {
                return this.areaFieldSpecified;
            }
            set {
                this.areaFieldSpecified = value;
                this.RaisePropertyChanged("AreaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal SpaceProfit {
            get {
                return this.spaceProfitField;
            }
            set {
                this.spaceProfitField = value;
                this.RaisePropertyChanged("SpaceProfit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpaceProfitSpecified {
            get {
                return this.spaceProfitFieldSpecified;
            }
            set {
                this.spaceProfitFieldSpecified = value;
                this.RaisePropertyChanged("SpaceProfitSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class SpaceProfitByCurrentIDQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantCodeField;
        
        private string layoutCodeField;
        
        private string gubunField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LayoutCode {
            get {
                return this.layoutCodeField;
            }
            set {
                this.layoutCodeField = value;
                this.RaisePropertyChanged("LayoutCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Gubun {
            get {
                return this.gubunField;
            }
            set {
                this.gubunField = value;
                this.RaisePropertyChanged("Gubun");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/SD", ConfigurationName="ZMANAGESPACEPROFITIN.ManageSpaceProfitIn")]
    public interface ManageSpaceProfitIn {
        
        // CODEGEN: Generating message contract since the operation SpaceProfitByCurrentIDQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse SpaceProfitByCurrentIDQueryResponse_In(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse> SpaceProfitByCurrentIDQueryResponse_InAsync(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SpaceProfitByCurrentIDQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryMessage_sync SpaceProfitByCurrentIDQuery_sync;
        
        public SpaceProfitByCurrentIDQueryResponse_InRequest() {
        }
        
        public SpaceProfitByCurrentIDQueryResponse_InRequest(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryMessage_sync SpaceProfitByCurrentIDQuery_sync) {
            this.SpaceProfitByCurrentIDQuery_sync = SpaceProfitByCurrentIDQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SpaceProfitByCurrentIDQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDResponseMessage_sync SpaceProfitByCurrentIDResponse_sync;
        
        public SpaceProfitByCurrentIDQueryResponse_InResponse() {
        }
        
        public SpaceProfitByCurrentIDQueryResponse_InResponse(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDResponseMessage_sync SpaceProfitByCurrentIDResponse_sync) {
            this.SpaceProfitByCurrentIDResponse_sync = SpaceProfitByCurrentIDResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageSpaceProfitInChannel : Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageSpaceProfitInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn>, Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn {
        
        public ManageSpaceProfitInClient() {
        }
        
        public ManageSpaceProfitInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageSpaceProfitInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSpaceProfitInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSpaceProfitInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn.SpaceProfitByCurrentIDQueryResponse_In(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest request) {
            return base.Channel.SpaceProfitByCurrentIDQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDResponseMessage_sync SpaceProfitByCurrentIDQueryResponse_In(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryMessage_sync SpaceProfitByCurrentIDQuery_sync) {
            Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest();
            inValue.SpaceProfitByCurrentIDQuery_sync = SpaceProfitByCurrentIDQuery_sync;
            Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse retVal = ((Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn)(this)).SpaceProfitByCurrentIDQueryResponse_In(inValue);
            return retVal.SpaceProfitByCurrentIDResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse> Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn.SpaceProfitByCurrentIDQueryResponse_InAsync(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest request) {
            return base.Channel.SpaceProfitByCurrentIDQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InResponse> SpaceProfitByCurrentIDQueryResponse_InAsync(Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryMessage_sync SpaceProfitByCurrentIDQuery_sync) {
            Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZMANAGESPACEPROFITIN.SpaceProfitByCurrentIDQueryResponse_InRequest();
            inValue.SpaceProfitByCurrentIDQuery_sync = SpaceProfitByCurrentIDQuery_sync;
            return ((Eland.NRSM.Template.ZMANAGESPACEPROFITIN.ManageSpaceProfitIn)(this)).SpaceProfitByCurrentIDQueryResponse_InAsync(inValue);
        }
    }
}
