//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZQUERYHISTORYIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class CompareList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gubunField;
        
        private string layoutCodeField;
        
        private string colorField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Gubun {
            get {
                return this.gubunField;
            }
            set {
                this.gubunField = value;
                this.RaisePropertyChanged("Gubun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LayoutCode {
            get {
                return this.layoutCodeField;
            }
            set {
                this.layoutCodeField = value;
                this.RaisePropertyChanged("LayoutCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class PlanList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gubunField;
        
        private string layoutCodeField;
        
        private decimal gSpaceSizeField;
        
        private bool gSpaceSizeFieldSpecified;
        
        private decimal nSpaceSizeField;
        
        private bool nSpaceSizeFieldSpecified;
        
        private string layoutNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Gubun {
            get {
                return this.gubunField;
            }
            set {
                this.gubunField = value;
                this.RaisePropertyChanged("Gubun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LayoutCode {
            get {
                return this.layoutCodeField;
            }
            set {
                this.layoutCodeField = value;
                this.RaisePropertyChanged("LayoutCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal GSpaceSize {
            get {
                return this.gSpaceSizeField;
            }
            set {
                this.gSpaceSizeField = value;
                this.RaisePropertyChanged("GSpaceSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GSpaceSizeSpecified {
            get {
                return this.gSpaceSizeFieldSpecified;
            }
            set {
                this.gSpaceSizeFieldSpecified = value;
                this.RaisePropertyChanged("GSpaceSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NSpaceSize {
            get {
                return this.nSpaceSizeField;
            }
            set {
                this.nSpaceSizeField = value;
                this.RaisePropertyChanged("NSpaceSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NSpaceSizeSpecified {
            get {
                return this.nSpaceSizeFieldSpecified;
            }
            set {
                this.nSpaceSizeFieldSpecified = value;
                this.RaisePropertyChanged("NSpaceSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LayoutName {
            get {
                return this.layoutNameField;
            }
            set {
                this.layoutNameField = value;
                this.RaisePropertyChanged("LayoutName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class HistoryByStoreComparisonElementsResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string messageField;
        
        private PlanList[] planList1Field;
        
        private PlanList[] planList2Field;
        
        private CompareList[] compareListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlanList1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PlanList[] PlanList1 {
            get {
                return this.planList1Field;
            }
            set {
                this.planList1Field = value;
                this.RaisePropertyChanged("PlanList1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlanList2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PlanList[] PlanList2 {
            get {
                return this.planList2Field;
            }
            set {
                this.planList2Field = value;
                this.RaisePropertyChanged("PlanList2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompareList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CompareList[] CompareList {
            get {
                return this.compareListField;
            }
            set {
                this.compareListField = value;
                this.RaisePropertyChanged("CompareList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class HistoryByStoreComparisonElementsQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantCodeField;
        
        private string floorField;
        
        private System.DateTime startDate1Field;
        
        private bool startDate1FieldSpecified;
        
        private System.DateTime startDate2Field;
        
        private bool startDate2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime StartDate1 {
            get {
                return this.startDate1Field;
            }
            set {
                this.startDate1Field = value;
                this.RaisePropertyChanged("StartDate1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDate1Specified {
            get {
                return this.startDate1FieldSpecified;
            }
            set {
                this.startDate1FieldSpecified = value;
                this.RaisePropertyChanged("StartDate1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime StartDate2 {
            get {
                return this.startDate2Field;
            }
            set {
                this.startDate2Field = value;
                this.RaisePropertyChanged("StartDate2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDate2Specified {
            get {
                return this.startDate2FieldSpecified;
            }
            set {
                this.startDate2FieldSpecified = value;
                this.RaisePropertyChanged("StartDate2Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/SD", ConfigurationName="ZQUERYHISTORYIN.QueryHistoryIn")]
    public interface QueryHistoryIn {
        
        // CODEGEN: Generating message contract since the operation HistoryByStoreComparisonElementsQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZQUERYHISTORYIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse HistoryByStoreComparisonElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse> HistoryByStoreComparisonElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HistoryByStoreComparisonElementsQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryMessage_sync HistoryByStoreComparisonElementsQuery_sync;
        
        public HistoryByStoreComparisonElementsQueryResponse_InRequest() {
        }
        
        public HistoryByStoreComparisonElementsQueryResponse_InRequest(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryMessage_sync HistoryByStoreComparisonElementsQuery_sync) {
            this.HistoryByStoreComparisonElementsQuery_sync = HistoryByStoreComparisonElementsQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HistoryByStoreComparisonElementsQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsResponseMessage_sync HistoryByStoreComparisonElementsResponse_sync;
        
        public HistoryByStoreComparisonElementsQueryResponse_InResponse() {
        }
        
        public HistoryByStoreComparisonElementsQueryResponse_InResponse(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsResponseMessage_sync HistoryByStoreComparisonElementsResponse_sync) {
            this.HistoryByStoreComparisonElementsResponse_sync = HistoryByStoreComparisonElementsResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryHistoryInChannel : Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryHistoryInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn>, Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn {
        
        public QueryHistoryInClient() {
        }
        
        public QueryHistoryInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryHistoryInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryHistoryInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryHistoryInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn.HistoryByStoreComparisonElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest request) {
            return base.Channel.HistoryByStoreComparisonElementsQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsResponseMessage_sync HistoryByStoreComparisonElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryMessage_sync HistoryByStoreComparisonElementsQuery_sync) {
            Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest();
            inValue.HistoryByStoreComparisonElementsQuery_sync = HistoryByStoreComparisonElementsQuery_sync;
            Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse retVal = ((Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn)(this)).HistoryByStoreComparisonElementsQueryResponse_In(inValue);
            return retVal.HistoryByStoreComparisonElementsResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse> Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn.HistoryByStoreComparisonElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest request) {
            return base.Channel.HistoryByStoreComparisonElementsQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InResponse> HistoryByStoreComparisonElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryMessage_sync HistoryByStoreComparisonElementsQuery_sync) {
            Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYHISTORYIN.HistoryByStoreComparisonElementsQueryResponse_InRequest();
            inValue.HistoryByStoreComparisonElementsQuery_sync = HistoryByStoreComparisonElementsQuery_sync;
            return ((Eland.NRSM.Template.ZQUERYHISTORYIN.QueryHistoryIn)(this)).HistoryByStoreComparisonElementsQueryResponse_InAsync(inValue);
        }
    }
}
