//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class StoreFloorList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantCodeField;
        
        private string plantCodeNameField;
        
        private string floorField;
        
        private string floorDescField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime enddateField;
        
        private bool enddateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PlantCodeName {
            get {
                return this.plantCodeNameField;
            }
            set {
                this.plantCodeNameField = value;
                this.RaisePropertyChanged("PlantCodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FloorDesc {
            get {
                return this.floorDescField;
            }
            set {
                this.floorDescField = value;
                this.RaisePropertyChanged("FloorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("StartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime Enddate {
            get {
                return this.enddateField;
            }
            set {
                this.enddateField = value;
                this.RaisePropertyChanged("Enddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnddateSpecified {
            get {
                return this.enddateFieldSpecified;
            }
            set {
                this.enddateFieldSpecified = value;
                this.RaisePropertyChanged("EnddateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class StoreFloorCodeByListResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string messageField;
        
        private StoreFloorList[] storeFloorListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StoreFloorList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public StoreFloorList[] StoreFloorList {
            get {
                return this.storeFloorListField;
            }
            set {
                this.storeFloorListField = value;
                this.RaisePropertyChanged("StoreFloorList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class StoreFloorCodeByListQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PersonNumber {
            get {
                return this.personNumberField;
            }
            set {
                this.personNumberField = value;
                this.RaisePropertyChanged("PersonNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/SD", ConfigurationName="ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000")]
    public interface QueryStoreFloorCodeIn_V1000 {
        
        // CODEGEN: Generating message contract since the operation StoreFloorCodeByListElementsQueryResponse_In_V1000 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response StoreFloorCodeByListElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response> StoreFloorCodeByListElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreFloorCodeByListElementsQueryResponse_In_V1000Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListQueryMessage_sync StoreFloorCodeByListQuery_sync;
        
        public StoreFloorCodeByListElementsQueryResponse_In_V1000Request() {
        }
        
        public StoreFloorCodeByListElementsQueryResponse_In_V1000Request(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListQueryMessage_sync StoreFloorCodeByListQuery_sync) {
            this.StoreFloorCodeByListQuery_sync = StoreFloorCodeByListQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreFloorCodeByListElementsQueryResponse_In_V1000Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListResponseMessage_sync StoreFloorCodeByListResponse_sync;
        
        public StoreFloorCodeByListElementsQueryResponse_In_V1000Response() {
        }
        
        public StoreFloorCodeByListElementsQueryResponse_In_V1000Response(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListResponseMessage_sync StoreFloorCodeByListResponse_sync) {
            this.StoreFloorCodeByListResponse_sync = StoreFloorCodeByListResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryStoreFloorCodeIn_V1000Channel : Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryStoreFloorCodeIn_V1000Client : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000>, Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000 {
        
        public QueryStoreFloorCodeIn_V1000Client() {
        }
        
        public QueryStoreFloorCodeIn_V1000Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryStoreFloorCodeIn_V1000Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryStoreFloorCodeIn_V1000Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryStoreFloorCodeIn_V1000Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request request) {
            return base.Channel.StoreFloorCodeByListElementsQueryResponse_In_V1000(request);
        }
        
        public Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListResponseMessage_sync StoreFloorCodeByListElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListQueryMessage_sync StoreFloorCodeByListQuery_sync) {
            Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request inValue = new Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request();
            inValue.StoreFloorCodeByListQuery_sync = StoreFloorCodeByListQuery_sync;
            Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response retVal = ((Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000)(this)).StoreFloorCodeByListElementsQueryResponse_In_V1000(inValue);
            return retVal.StoreFloorCodeByListResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response> Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request request) {
            return base.Channel.StoreFloorCodeByListElementsQueryResponse_In_V1000Async(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Response> StoreFloorCodeByListElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListQueryMessage_sync StoreFloorCodeByListQuery_sync) {
            Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request inValue = new Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.StoreFloorCodeByListElementsQueryResponse_In_V1000Request();
            inValue.StoreFloorCodeByListQuery_sync = StoreFloorCodeByListQuery_sync;
            return ((Eland.NRSM.Template.ZQUERYSTOREFLOORCODEIN_V1000.QueryStoreFloorCodeIn_V1000)(this)).StoreFloorCodeByListElementsQueryResponse_In_V1000Async(inValue);
        }
    }
}
