//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZQUERYUSERAUTHIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class UserAuthList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bNAMEField;
        
        private string vALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BNAME {
            get {
                return this.bNAMEField;
            }
            set {
                this.bNAMEField = value;
                this.RaisePropertyChanged("BNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class UserAuthResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bNAMEField;
        
        private string wERKSField;
        
        private UserAuthList[] pLANTUserAuthListField;
        
        private UserAuthList[] cUUserAuthListField;
        
        private UserAuthList[] yEARUserAuthListField;
        
        private string flagField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BNAME {
            get {
                return this.bNAMEField;
            }
            set {
                this.bNAMEField = value;
                this.RaisePropertyChanged("BNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PLANTUserAuthList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public UserAuthList[] PLANTUserAuthList {
            get {
                return this.pLANTUserAuthListField;
            }
            set {
                this.pLANTUserAuthListField = value;
                this.RaisePropertyChanged("PLANTUserAuthList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CUUserAuthList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UserAuthList[] CUUserAuthList {
            get {
                return this.cUUserAuthListField;
            }
            set {
                this.cUUserAuthListField = value;
                this.RaisePropertyChanged("CUUserAuthList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEARUserAuthList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public UserAuthList[] YEARUserAuthList {
            get {
                return this.yEARUserAuthListField;
            }
            set {
                this.yEARUserAuthListField = value;
                this.RaisePropertyChanged("YEARUserAuthList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class UserAuthQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
                this.RaisePropertyChanged("PERNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/MOB", ConfigurationName="ZQUERYUSERAUTHIN.QueryUserAuthIn")]
    public interface QueryUserAuthIn {
        
        // CODEGEN: 操作 UserAuthQueryResponse_In 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZQUERYUSERAUTHIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse UserAuthQueryResponse_In(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse> UserAuthQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQuery_sync UserAuthQuery_sync;
        
        public UserAuthQueryResponse_InRequest() {
        }
        
        public UserAuthQueryResponse_InRequest(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQuery_sync UserAuthQuery_sync) {
            this.UserAuthQuery_sync = UserAuthQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthResponse_sync UserAuthResponse_sync;
        
        public UserAuthQueryResponse_InResponse() {
        }
        
        public UserAuthQueryResponse_InResponse(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthResponse_sync UserAuthResponse_sync) {
            this.UserAuthResponse_sync = UserAuthResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryUserAuthInChannel : Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryUserAuthInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn>, Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn {
        
        public QueryUserAuthInClient() {
        }
        
        public QueryUserAuthInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryUserAuthInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryUserAuthInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryUserAuthInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn.UserAuthQueryResponse_In(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest request) {
            return base.Channel.UserAuthQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthResponse_sync UserAuthQueryResponse_In(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQuery_sync UserAuthQuery_sync) {
            Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest();
            inValue.UserAuthQuery_sync = UserAuthQuery_sync;
            Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse retVal = ((Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn)(this)).UserAuthQueryResponse_In(inValue);
            return retVal.UserAuthResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse> Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn.UserAuthQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest request) {
            return base.Channel.UserAuthQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InResponse> UserAuthQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQuery_sync UserAuthQuery_sync) {
            Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYUSERAUTHIN.UserAuthQueryResponse_InRequest();
            inValue.UserAuthQuery_sync = UserAuthQuery_sync;
            return ((Eland.NRSM.Template.ZQUERYUSERAUTHIN.QueryUserAuthIn)(this)).UserAuthQueryResponse_InAsync(inValue);
        }
    }
}
