//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZQUERYFLOORREVENUEIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class RevenueIFList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string calcTypeField;
        
        private string reportCodeField;
        
        private string gradeField;
        
        private decimal valueFromField;
        
        private bool valueFromFieldSpecified;
        
        private decimal valueToField;
        
        private bool valueToFieldSpecified;
        
        private string colorField;
        
        private string textField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal percentField;
        
        private bool percentFieldSpecified;
        
        private int sequenceField;
        
        private bool sequenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CalcType {
            get {
                return this.calcTypeField;
            }
            set {
                this.calcTypeField = value;
                this.RaisePropertyChanged("CalcType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReportCode {
            get {
                return this.reportCodeField;
            }
            set {
                this.reportCodeField = value;
                this.RaisePropertyChanged("ReportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("Grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal ValueFrom {
            get {
                return this.valueFromField;
            }
            set {
                this.valueFromField = value;
                this.RaisePropertyChanged("ValueFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueFromSpecified {
            get {
                return this.valueFromFieldSpecified;
            }
            set {
                this.valueFromFieldSpecified = value;
                this.RaisePropertyChanged("ValueFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal ValueTo {
            get {
                return this.valueToField;
            }
            set {
                this.valueToField = value;
                this.RaisePropertyChanged("ValueTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueToSpecified {
            get {
                return this.valueToFieldSpecified;
            }
            set {
                this.valueToFieldSpecified = value;
                this.RaisePropertyChanged("ValueToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
                this.RaisePropertyChanged("Percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified {
            get {
                return this.percentFieldSpecified;
            }
            set {
                this.percentFieldSpecified = value;
                this.RaisePropertyChanged("PercentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SequenceSpecified {
            get {
                return this.sequenceFieldSpecified;
            }
            set {
                this.sequenceFieldSpecified = value;
                this.RaisePropertyChanged("SequenceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class RevenueStoreInfoList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string layoutCodeField;
        
        private string shapeIDField;
        
        private string areaTypeField;
        
        private string reportCodeField;
        
        private string calcTypeField;
        
        private decimal valueField;
        
        private bool valueFieldSpecified;
        
        private string colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LayoutCode {
            get {
                return this.layoutCodeField;
            }
            set {
                this.layoutCodeField = value;
                this.RaisePropertyChanged("LayoutCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ShapeID {
            get {
                return this.shapeIDField;
            }
            set {
                this.shapeIDField = value;
                this.RaisePropertyChanged("ShapeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AreaType {
            get {
                return this.areaTypeField;
            }
            set {
                this.areaTypeField = value;
                this.RaisePropertyChanged("AreaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ReportCode {
            get {
                return this.reportCodeField;
            }
            set {
                this.reportCodeField = value;
                this.RaisePropertyChanged("ReportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CalcType {
            get {
                return this.calcTypeField;
            }
            set {
                this.calcTypeField = value;
                this.RaisePropertyChanged("CalcType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("ValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class RevenueCurrentList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string layoutCodeField;
        
        private string shapeIDField;
        
        private decimal gSpaceSizeField;
        
        private bool gSpaceSizeFieldSpecified;
        
        private decimal nSpaceSizeField;
        
        private bool nSpaceSizeFieldSpecified;
        
        private decimal goalSumField;
        
        private bool goalSumFieldSpecified;
        
        private string layoutModuleNameField;
        
        private decimal saleSumField;
        
        private bool saleSumFieldSpecified;
        
        private decimal profitSumField;
        
        private bool profitSumFieldSpecified;
        
        private decimal profitPercentField;
        
        private bool profitPercentFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LayoutCode {
            get {
                return this.layoutCodeField;
            }
            set {
                this.layoutCodeField = value;
                this.RaisePropertyChanged("LayoutCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ShapeID {
            get {
                return this.shapeIDField;
            }
            set {
                this.shapeIDField = value;
                this.RaisePropertyChanged("ShapeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal GSpaceSize {
            get {
                return this.gSpaceSizeField;
            }
            set {
                this.gSpaceSizeField = value;
                this.RaisePropertyChanged("GSpaceSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GSpaceSizeSpecified {
            get {
                return this.gSpaceSizeFieldSpecified;
            }
            set {
                this.gSpaceSizeFieldSpecified = value;
                this.RaisePropertyChanged("GSpaceSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NSpaceSize {
            get {
                return this.nSpaceSizeField;
            }
            set {
                this.nSpaceSizeField = value;
                this.RaisePropertyChanged("NSpaceSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NSpaceSizeSpecified {
            get {
                return this.nSpaceSizeFieldSpecified;
            }
            set {
                this.nSpaceSizeFieldSpecified = value;
                this.RaisePropertyChanged("NSpaceSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal GoalSum {
            get {
                return this.goalSumField;
            }
            set {
                this.goalSumField = value;
                this.RaisePropertyChanged("GoalSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GoalSumSpecified {
            get {
                return this.goalSumFieldSpecified;
            }
            set {
                this.goalSumFieldSpecified = value;
                this.RaisePropertyChanged("GoalSumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LayoutModuleName {
            get {
                return this.layoutModuleNameField;
            }
            set {
                this.layoutModuleNameField = value;
                this.RaisePropertyChanged("LayoutModuleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal SaleSum {
            get {
                return this.saleSumField;
            }
            set {
                this.saleSumField = value;
                this.RaisePropertyChanged("SaleSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleSumSpecified {
            get {
                return this.saleSumFieldSpecified;
            }
            set {
                this.saleSumFieldSpecified = value;
                this.RaisePropertyChanged("SaleSumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal ProfitSum {
            get {
                return this.profitSumField;
            }
            set {
                this.profitSumField = value;
                this.RaisePropertyChanged("ProfitSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitSumSpecified {
            get {
                return this.profitSumFieldSpecified;
            }
            set {
                this.profitSumFieldSpecified = value;
                this.RaisePropertyChanged("ProfitSumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal ProfitPercent {
            get {
                return this.profitPercentField;
            }
            set {
                this.profitPercentField = value;
                this.RaisePropertyChanged("ProfitPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfitPercentSpecified {
            get {
                return this.profitPercentFieldSpecified;
            }
            set {
                this.profitPercentFieldSpecified = value;
                this.RaisePropertyChanged("ProfitPercentSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class FloorRevenueByResultElementsResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string messageField;
        
        private RevenueCurrentList[] revenueCurrentListField;
        
        private RevenueStoreInfoList[] revenueStoreInfoListField;
        
        private RevenueIFList[] revenueIfListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevenueCurrentList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RevenueCurrentList[] RevenueCurrentList {
            get {
                return this.revenueCurrentListField;
            }
            set {
                this.revenueCurrentListField = value;
                this.RaisePropertyChanged("RevenueCurrentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevenueStoreInfoList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public RevenueStoreInfoList[] RevenueStoreInfoList {
            get {
                return this.revenueStoreInfoListField;
            }
            set {
                this.revenueStoreInfoListField = value;
                this.RaisePropertyChanged("RevenueStoreInfoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevenueIfList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public RevenueIFList[] RevenueIfList {
            get {
                return this.revenueIfListField;
            }
            set {
                this.revenueIfListField = value;
                this.RaisePropertyChanged("RevenueIfList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class FloorRevenueByResultElementsQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantCodeField;
        
        private string floorField;
        
        private string yearMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string YearMonth {
            get {
                return this.yearMonthField;
            }
            set {
                this.yearMonthField = value;
                this.RaisePropertyChanged("YearMonth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/SD", ConfigurationName="ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn")]
    public interface QueryFloorRevenueIn {
        
        // CODEGEN: Generating message contract since the operation FloorRevenueByResultElementsQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse FloorRevenueByResultElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse> FloorRevenueByResultElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FloorRevenueByResultElementsQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryMessage_sync FloorRevenueByResultElementsQuery_sync;
        
        public FloorRevenueByResultElementsQueryResponse_InRequest() {
        }
        
        public FloorRevenueByResultElementsQueryResponse_InRequest(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryMessage_sync FloorRevenueByResultElementsQuery_sync) {
            this.FloorRevenueByResultElementsQuery_sync = FloorRevenueByResultElementsQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FloorRevenueByResultElementsQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsResponseMessage_sync FloorRevenueByResultElementsResponse_sync;
        
        public FloorRevenueByResultElementsQueryResponse_InResponse() {
        }
        
        public FloorRevenueByResultElementsQueryResponse_InResponse(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsResponseMessage_sync FloorRevenueByResultElementsResponse_sync) {
            this.FloorRevenueByResultElementsResponse_sync = FloorRevenueByResultElementsResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryFloorRevenueInChannel : Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryFloorRevenueInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn>, Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn {
        
        public QueryFloorRevenueInClient() {
        }
        
        public QueryFloorRevenueInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryFloorRevenueInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryFloorRevenueInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryFloorRevenueInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn.FloorRevenueByResultElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest request) {
            return base.Channel.FloorRevenueByResultElementsQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsResponseMessage_sync FloorRevenueByResultElementsQueryResponse_In(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryMessage_sync FloorRevenueByResultElementsQuery_sync) {
            Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest();
            inValue.FloorRevenueByResultElementsQuery_sync = FloorRevenueByResultElementsQuery_sync;
            Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse retVal = ((Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn)(this)).FloorRevenueByResultElementsQueryResponse_In(inValue);
            return retVal.FloorRevenueByResultElementsResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse> Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn.FloorRevenueByResultElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest request) {
            return base.Channel.FloorRevenueByResultElementsQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InResponse> FloorRevenueByResultElementsQueryResponse_InAsync(Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryMessage_sync FloorRevenueByResultElementsQuery_sync) {
            Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest inValue = new Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.FloorRevenueByResultElementsQueryResponse_InRequest();
            inValue.FloorRevenueByResultElementsQuery_sync = FloorRevenueByResultElementsQuery_sync;
            return ((Eland.NRSM.Template.ZQUERYFLOORREVENUEIN.QueryFloorRevenueIn)(this)).FloorRevenueByResultElementsQueryResponse_InAsync(inValue);
        }
    }
}
