//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class RevenueResultList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal totalField;
        
        private bool totalFieldSpecified;
        
        private string plantCodeField;
        
        private string plantNameField;
        
        private string categoryUnitField;
        
        private string categoryUnitNameField;
        
        private string purchaseGroupField;
        
        private string purchaseGroupNameField;
        
        private string brandCodeField;
        
        private string brandNameField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal goalAmountField;
        
        private bool goalAmountFieldSpecified;
        
        private decimal rateField;
        
        private bool rateFieldSpecified;
        
        private decimal pastAmountField;
        
        private bool pastAmountFieldSpecified;
        
        private decimal growthRateField;
        
        private bool growthRateFieldSpecified;
        
        private decimal spaceSumField;
        
        private bool spaceSumFieldSpecified;
        
        private decimal spaceProfitField;
        
        private bool spaceProfitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("TotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PlantName {
            get {
                return this.plantNameField;
            }
            set {
                this.plantNameField = value;
                this.RaisePropertyChanged("PlantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CategoryUnit {
            get {
                return this.categoryUnitField;
            }
            set {
                this.categoryUnitField = value;
                this.RaisePropertyChanged("CategoryUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CategoryUnitName {
            get {
                return this.categoryUnitNameField;
            }
            set {
                this.categoryUnitNameField = value;
                this.RaisePropertyChanged("CategoryUnitName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PurchaseGroup {
            get {
                return this.purchaseGroupField;
            }
            set {
                this.purchaseGroupField = value;
                this.RaisePropertyChanged("PurchaseGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PurchaseGroupName {
            get {
                return this.purchaseGroupNameField;
            }
            set {
                this.purchaseGroupNameField = value;
                this.RaisePropertyChanged("PurchaseGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
                this.RaisePropertyChanged("BrandCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
                this.RaisePropertyChanged("BrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal GoalAmount {
            get {
                return this.goalAmountField;
            }
            set {
                this.goalAmountField = value;
                this.RaisePropertyChanged("GoalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GoalAmountSpecified {
            get {
                return this.goalAmountFieldSpecified;
            }
            set {
                this.goalAmountFieldSpecified = value;
                this.RaisePropertyChanged("GoalAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified {
            get {
                return this.rateFieldSpecified;
            }
            set {
                this.rateFieldSpecified = value;
                this.RaisePropertyChanged("RateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal PastAmount {
            get {
                return this.pastAmountField;
            }
            set {
                this.pastAmountField = value;
                this.RaisePropertyChanged("PastAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PastAmountSpecified {
            get {
                return this.pastAmountFieldSpecified;
            }
            set {
                this.pastAmountFieldSpecified = value;
                this.RaisePropertyChanged("PastAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal GrowthRate {
            get {
                return this.growthRateField;
            }
            set {
                this.growthRateField = value;
                this.RaisePropertyChanged("GrowthRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrowthRateSpecified {
            get {
                return this.growthRateFieldSpecified;
            }
            set {
                this.growthRateFieldSpecified = value;
                this.RaisePropertyChanged("GrowthRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal SpaceSum {
            get {
                return this.spaceSumField;
            }
            set {
                this.spaceSumField = value;
                this.RaisePropertyChanged("SpaceSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpaceSumSpecified {
            get {
                return this.spaceSumFieldSpecified;
            }
            set {
                this.spaceSumFieldSpecified = value;
                this.RaisePropertyChanged("SpaceSumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal SpaceProfit {
            get {
                return this.spaceProfitField;
            }
            set {
                this.spaceProfitField = value;
                this.RaisePropertyChanged("SpaceProfit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpaceProfitSpecified {
            get {
                return this.spaceProfitFieldSpecified;
            }
            set {
                this.spaceProfitFieldSpecified = value;
                this.RaisePropertyChanged("SpaceProfitSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class SalesResultByResultInfoResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string messageField;
        
        private RevenueResultList[] revenueResultListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RevenueResultList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RevenueResultList[] RevenueResultList {
            get {
                return this.revenueResultListField;
            }
            set {
                this.revenueResultListField = value;
                this.RaisePropertyChanged("RevenueResultList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class SalesResultByResultInfoQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gubunField;
        
        private string personNumberField;
        
        private string plantCodeField;
        
        private string yearMonthField;
        
        private string categoryUnitField;
        
        private string purchaseGroupField;
        
        private string brandCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Gubun {
            get {
                return this.gubunField;
            }
            set {
                this.gubunField = value;
                this.RaisePropertyChanged("Gubun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PersonNumber {
            get {
                return this.personNumberField;
            }
            set {
                this.personNumberField = value;
                this.RaisePropertyChanged("PersonNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
                this.RaisePropertyChanged("PlantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string YearMonth {
            get {
                return this.yearMonthField;
            }
            set {
                this.yearMonthField = value;
                this.RaisePropertyChanged("YearMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CategoryUnit {
            get {
                return this.categoryUnitField;
            }
            set {
                this.categoryUnitField = value;
                this.RaisePropertyChanged("CategoryUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PurchaseGroup {
            get {
                return this.purchaseGroupField;
            }
            set {
                this.purchaseGroupField = value;
                this.RaisePropertyChanged("PurchaseGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
                this.RaisePropertyChanged("BrandCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/SD", ConfigurationName="ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000")]
    public interface QuerySalesResultIn_V1000 {
        
        // CODEGEN: Generating message contract since the operation SalesResultByResultInfoElementsQueryResponse_In_V1000 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response SalesResultByResultInfoElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response> SalesResultByResultInfoElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesResultByResultInfoElementsQueryResponse_In_V1000Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoQueryMessage_sync SalesResultByResultInfoQuery_sync;
        
        public SalesResultByResultInfoElementsQueryResponse_In_V1000Request() {
        }
        
        public SalesResultByResultInfoElementsQueryResponse_In_V1000Request(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoQueryMessage_sync SalesResultByResultInfoQuery_sync) {
            this.SalesResultByResultInfoQuery_sync = SalesResultByResultInfoQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesResultByResultInfoElementsQueryResponse_In_V1000Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/SD", Order=0)]
        public Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoResponseMessage_sync SalesResultByResultInfoResponse_sync;
        
        public SalesResultByResultInfoElementsQueryResponse_In_V1000Response() {
        }
        
        public SalesResultByResultInfoElementsQueryResponse_In_V1000Response(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoResponseMessage_sync SalesResultByResultInfoResponse_sync) {
            this.SalesResultByResultInfoResponse_sync = SalesResultByResultInfoResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuerySalesResultIn_V1000Channel : Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuerySalesResultIn_V1000Client : System.ServiceModel.ClientBase<Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000>, Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000 {
        
        public QuerySalesResultIn_V1000Client() {
        }
        
        public QuerySalesResultIn_V1000Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuerySalesResultIn_V1000Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySalesResultIn_V1000Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuerySalesResultIn_V1000Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request request) {
            return base.Channel.SalesResultByResultInfoElementsQueryResponse_In_V1000(request);
        }
        
        public Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoResponseMessage_sync SalesResultByResultInfoElementsQueryResponse_In_V1000(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoQueryMessage_sync SalesResultByResultInfoQuery_sync) {
            Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request inValue = new Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request();
            inValue.SalesResultByResultInfoQuery_sync = SalesResultByResultInfoQuery_sync;
            Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response retVal = ((Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000)(this)).SalesResultByResultInfoElementsQueryResponse_In_V1000(inValue);
            return retVal.SalesResultByResultInfoResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response> Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request request) {
            return base.Channel.SalesResultByResultInfoElementsQueryResponse_In_V1000Async(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Response> SalesResultByResultInfoElementsQueryResponse_In_V1000Async(Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoQueryMessage_sync SalesResultByResultInfoQuery_sync) {
            Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request inValue = new Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.SalesResultByResultInfoElementsQueryResponse_In_V1000Request();
            inValue.SalesResultByResultInfoQuery_sync = SalesResultByResultInfoQuery_sync;
            return ((Eland.NRSM.Template.ZQUERYSALESRESULTIN_V1000.QuerySalesResultIn_V1000)(this)).SalesResultByResultInfoElementsQueryResponse_In_V1000Async(inValue);
        }
    }
}
