//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eland.NRSM.Template.QUERYPREVSAMEDATEIN {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SAPGlobal/Global")]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/SD")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class PrevSameDateResponse_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagField;
        
        private string returnMessageField;
        
        private System.DateTime outDAYField;
        
        private bool outDAYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime OutDAY {
            get {
                return this.outDAYField;
            }
            set {
                this.outDAYField = value;
                this.RaisePropertyChanged("OutDAY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutDAYSpecified {
            get {
                return this.outDAYFieldSpecified;
            }
            set {
                this.outDAYFieldSpecified = value;
                this.RaisePropertyChanged("OutDAYSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eland.co.kr/KRERP/MOB")]
    public partial class PrevSameDateQuery_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime inDAYField;
        
        private bool inDAYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime InDAY {
            get {
                return this.inDAYField;
            }
            set {
                this.inDAYField = value;
                this.RaisePropertyChanged("InDAY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InDAYSpecified {
            get {
                return this.inDAYFieldSpecified;
            }
            set {
                this.inDAYFieldSpecified = value;
                this.RaisePropertyChanged("InDAYSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eland.co.kr/KRERP/MOB", ConfigurationName="QUERYPREVSAMEDATEIN.QueryPrevSameDateIn")]
    public interface QueryPrevSameDateIn {
        
        // CODEGEN: Generating message contract since the operation PrevSameDateQueryResponse_In is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.StandardMessageFault), Action="", Name="StandardMessageFault", Namespace="http://sap.com/xi/SAPGlobal/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse PrevSameDateQueryResponse_In(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse> PrevSameDateQueryResponse_InAsync(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevSameDateQueryResponse_InRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQuery_sync PrevSameDateQuery_sync;
        
        public PrevSameDateQueryResponse_InRequest() {
        }
        
        public PrevSameDateQueryResponse_InRequest(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQuery_sync PrevSameDateQuery_sync) {
            this.PrevSameDateQuery_sync = PrevSameDateQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevSameDateQueryResponse_InResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eland.co.kr/KRERP/MOB", Order=0)]
        public Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateResponse_sync PrevSameDateResponse_sync;
        
        public PrevSameDateQueryResponse_InResponse() {
        }
        
        public PrevSameDateQueryResponse_InResponse(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateResponse_sync PrevSameDateResponse_sync) {
            this.PrevSameDateResponse_sync = PrevSameDateResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryPrevSameDateInChannel : Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryPrevSameDateInClient : System.ServiceModel.ClientBase<Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn>, Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn {
        
        public QueryPrevSameDateInClient() {
        }
        
        public QueryPrevSameDateInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryPrevSameDateInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPrevSameDateInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPrevSameDateInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn.PrevSameDateQueryResponse_In(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest request) {
            return base.Channel.PrevSameDateQueryResponse_In(request);
        }
        
        public Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateResponse_sync PrevSameDateQueryResponse_In(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQuery_sync PrevSameDateQuery_sync) {
            Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest inValue = new Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest();
            inValue.PrevSameDateQuery_sync = PrevSameDateQuery_sync;
            Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse retVal = ((Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn)(this)).PrevSameDateQueryResponse_In(inValue);
            return retVal.PrevSameDateResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse> Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn.PrevSameDateQueryResponse_InAsync(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest request) {
            return base.Channel.PrevSameDateQueryResponse_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InResponse> PrevSameDateQueryResponse_InAsync(Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQuery_sync PrevSameDateQuery_sync) {
            Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest inValue = new Eland.NRSM.Template.QUERYPREVSAMEDATEIN.PrevSameDateQueryResponse_InRequest();
            inValue.PrevSameDateQuery_sync = PrevSameDateQuery_sync;
            return ((Eland.NRSM.Template.QUERYPREVSAMEDATEIN.QueryPrevSameDateIn)(this)).PrevSameDateQueryResponse_InAsync(inValue);
        }
    }
}
